#https://mise.jdx.dev/registry.html
[tools]
java = "latest"
node = "latest"
python = "latest"
rust = "latest"
yarn = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gcloud = "latest"
github-cli = "latest"
go = "latest"
jq = "latest"
kubectl = "latest"
neovim = "latest"
pnpm = "latest"
starship = "latest"
terraform = "latest"
terragrunt = "latest"
tflint = "latest"
k9s = "latest"
opentofu = "latest"
kind = "latest"
aws-vault = "latest"

[tasks."terraform:init"]
description = "Initializes a Terraform working directory"
run = "terraform -chdir=terraform init"

[tasks."terraform:plan"]
description = "Generates an execution plan for Terraform"
run = "terraform -chdir=terraform plan"

[tasks."terraform:apply"]
description = "Applies the changes required to reach the desired state of the configuration"
run = "terraform -chdir=terraform apply"

[tasks."terraform:destroy"]
description = "Destroy Terraform-managed infrastructure"
run = "terraform -chdir=terraform destroy"

[tasks."terraform:validate"]
description = "Validates the Terraform files"
run = "terraform -chdir=terraform validate"

[tasks."terraform:format"]
description = "Formats the Terraform files"
run = "terraform -chdir=terraform fmt"

[tasks."terraform:check"]
description = "Checks the Terraform files"
depends = ["terraform:format", "terraform:validate"]

[env]
_.file = ".env"
